### ISSUE TITLE
Delegate the execution to a custom ExecutorService of VT

### ISSUE THREAD

**Issue by ceremo** [verhas/vtstream#2]
Hi,

we have custom `ExecutorService`'s creating virtual threads with additional features that we want to maintain to be used in the `ThreadedStream`. It would be great to have an additional constructor method in the `ThreadedStream` with a new parameter(`ExecutorService`), in order to delegate the execution of tasks to it. If it's not present, use instead the current `Thread.startVirtualThread(...)`.

What are your thoughts on this? I could create a PR to contribute it.

**Comment by ceremo** [comment]
I created this [PR](https://github.com/verhas/vtstream/pull/3)

**Comment by verhas** [comment]
I merged your change, I bravely assumed that it works ;-)

Asa far as I can tell after a cursory reading of the code it does not provide extra functionality to specify the executor service, it just uses the one instead of creating the virtual threads one by one, which I am not fully convinced is needed anyway or is better than creating the virtual threads if there is no extra configuration option.

**Comment by ceremo** [comment]
The custom ExecutorService can be defined [here](https://github.com/verhas/vtstream/blob/44794022fba955b83b45277dc0e422489c065c09/src/main/java/javax0/vtstream/ThreadedStream.java#L117)

**Comment by verhas** [comment]
I missed that. Great. Thanks!

**Comment by verhas** [comment]
I released 1.1.0 containing your addition

**Comment by ceremo** [comment]
Thanks @verhas
